name: 4count
services:
  postgres:
    image: postgres
    container_name: postgres-4count
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: public
    ports:
      - 6000:5432